import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api, messageOf } from "../services/api";
import { fmtTime, hours, Spinner, StatusBadge } from "../components/ui";

function inputDate(value) { if (!value) return ""; const date = new Date(value); date.setMinutes(date.getMinutes() - date.getTimezoneOffset()); return date.toISOString().slice(0, 16); }
export default function AttendanceDetail() {
  const { id } = useParams(), navigate = useNavigate();
  const [data, setData] = useState(), [form, setForm] = useState({}), [error, setError] = useState(""), [notice, setNotice] = useState(""), [saving, setSaving] = useState(false);
  const load = () => api.get(`/attendance/${id}`).then((response) => { const record = response.data; setData(record); setForm({ attendanceType: record.leaveType || "present", actualClockIn: inputDate(record.actualClockIn), actualClockOut: inputDate(record.actualClockOut), reason: "", reopen: false }); });
  useEffect(() => { load(); }, [id]);
  if (!data) return <Spinner/>;
  async function save(event) { event.preventDefault(); setSaving(true); setError(""); setNotice(""); try { await api.put(`/attendance/${id}`, form); await load(); setNotice("Attendance updated. Payroll calculations now use this change."); } catch (e) { setError(messageOf(e)); } finally { setSaving(false); } }
  const isLeave = form.attendanceType !== "present";
  return <><button className="text-sm text-brand-600" onClick={() => navigate(-1)}>← Back</button><div className="my-5"><h1 className="page-title">{data.employee?.name} · {data.workDate}</h1><div className="mt-2 flex gap-2">{data.conditions.map((x) => <StatusBadge key={x} value={x}/>)}</div></div>{notice && <div className="mb-4 rounded-lg bg-green-50 p-3 text-green-700">{notice}</div>}<div className="grid gap-6 lg:grid-cols-2">
    <div className="card p-6"><h2 className="font-bold">Calculated attendance</h2><div className="mt-5 grid grid-cols-2 gap-5">{[["Expected in", fmtTime(data.expectedClockIn)], ["Expected out", fmtTime(data.expectedClockOut)], ["Actual in", fmtTime(data.actualClockIn)], ["Actual out", fmtTime(data.actualClockOut)], ["Working time", hours(data.actualMinutes)], ["Late", hours(data.lateMinutes)], ["Short", hours(data.shortMinutes)], ["Overtime", hours(data.overtimeMinutes)]].map(([key, value]) => <div key={key}><div className="text-xs text-slate-400">{key}</div><div className="font-semibold">{value}</div></div>)}</div><div className="mt-6 border-t pt-4 text-sm text-slate-500">{data.sourcePunchIds.length} original punches linked. Original machine punches are never changed.</div></div>
    <form onSubmit={save} className="card p-6"><h2 className="font-bold">Manual adjustment or leave</h2>{error && <div className="mt-3 rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</div>}<label className="mt-4 block"><span className="label">Attendance type</span><select className="field" value={form.attendanceType} onChange={(e) => setForm({ ...form, attendanceType: e.target.value })}><option value="present">Present / time correction</option><option value="sick">Sick Leave</option><option value="casual">Casual Leave</option></select></label>{!isLeave && <><label className="mt-4 block"><span className="label">Actual clock in</span><input className="field" type="datetime-local" value={form.actualClockIn} onChange={(e) => setForm({ ...form, actualClockIn: e.target.value })}/></label><label className="mt-4 block"><span className="label">Actual clock out</span><input className="field" type="datetime-local" value={form.actualClockOut} onChange={(e) => setForm({ ...form, actualClockOut: e.target.value })}/></label></>}<label className="mt-4 block"><span className="label">Reason (required)</span><textarea className="field" placeholder={isLeave ? "Example: Sick leave approved by HR" : "Example: Employee forgot to clock out"} value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} required/></label>{data.workflow === "finalized" && <label className="mt-4 flex gap-2 text-sm"><input type="checkbox" checked={form.reopen} onChange={(e) => setForm({ ...form, reopen: e.target.checked })}/>Explicitly reopen finalized record</label>}<button disabled={saving} className="btn-primary mt-5">{saving ? "Saving…" : isLeave ? "Save leave" : "Save and recalculate"}</button></form>
  </div></>;
}
