import {Router} from 'express';import multer from 'multer';import {Attendance,AttendanceAdjustment,AttendanceException,Employee,ImportBatch,RawPunch,Settings,Shift} from '../models/index.js';import {AppError,asyncHandler,pageMeta} from '../utils/http.js';import {DEFAULT_MAPPING,importWorkbook,inspectWorkbook,processBatch} from '../services/importService.js';import {calculateAttendance} from '../services/attendanceProcessor.js';import {scheduleForDay} from '../services/companySchedule.js';const r=Router(),upload=multer({storage:multer.memoryStorage(),limits:{fileSize:15*1024*1024},fileFilter:(req,file,cb)=>cb(null,/\.xlsx?$/i.test(file.originalname))});
const validDate=value=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(value||''))return false;const date=new Date(`${value}T12:00:00`);return !Number.isNaN(date.valueOf())&&dateKey(date)===value;};
const dateKey=date=>[date.getFullYear(),String(date.getMonth()+1).padStart(2,'0'),String(date.getDate()).padStart(2,'0')].join('-');
function manualPunches(clockIn,clockOut){const punches=[],start=clockIn?new Date(clockIn):null,end=clockOut?new Date(clockOut):null;if(start&&Number.isNaN(start.valueOf())||end&&Number.isNaN(end.valueOf()))throw new AppError(422,'Choose valid clock-in and clock-out times');if(start&&end&&end<=start)throw new AppError(422,'Clock-out must be after clock-in');if(start)punches.push({_id:null,punchDateTime:start});if(end)punches.push({_id:null,punchDateTime:end});return punches;}
async function companyShift(workDate){const day=new Date(`${workDate}T12:00:00`).getDay(),settings=await Settings.findOne({key:'global'}).lean(),schedule=scheduleForDay(day,settings?.attendanceGrace);return Shift.findOneAndUpdate({name:schedule.name},{$set:{...schedule,active:true,processingWindowBeforeMinutes:240,processingWindowAfterMinutes:240}},{upsert:true,new:true,setDefaultsOnInsert:true});}
function leaveValues(employee,shift,workDate,leaveType){const calc=calculateAttendance({employee,shift,workDate,punches:[]}),label=leaveType==='sick'?'Sick Leave':'Casual Leave';return{...calc,actualClockIn:null,actualClockOut:null,actualMinutes:0,lateMinutes:0,earlyLeaveMinutes:0,shortMinutes:0,overtimeMinutes:0,conditions:['Leave',label],status:label,leaveType,workflow:'reviewed'};}
r.post('/inspect',upload.single('file'),asyncHandler(async(req,res)=>{if(!req.file)throw new AppError(400,'Choose an Excel file');res.json({...inspectWorkbook(req.file.buffer),suggestedMapping:DEFAULT_MAPPING});}));
r.post('/import',upload.single('file'),asyncHandler(async(req,res)=>{if(!req.file)throw new AppError(400,'Choose an Excel file');let mapping;try{mapping=req.body.mapping?JSON.parse(req.body.mapping):DEFAULT_MAPPING;}catch{throw new AppError(400,'Column mapping is invalid');}res.status(201).json(await importWorkbook({buffer:req.file.buffer,filename:req.file.originalname,mapping,userId:req.user._id}));}));
r.post('/process',asyncHandler(async(req,res)=>res.json(await processBatch(req.body.importId,{overwrite:!!req.body.overwrite}))));
r.post('/manual',asyncHandler(async(req,res)=>{const{employee:id,workDate,attendanceType='present',actualClockIn,actualClockOut,reason}=req.body;if(!id||!validDate(workDate))throw new AppError(422,'Employee and a valid date are required');if(!reason?.trim())throw new AppError(422,'An adjustment reason is required');if(!['present','sick','casual'].includes(attendanceType))throw new AppError(422,'Choose Present, Sick Leave or Casual Leave');const employee=await Employee.findById(id);if(!employee)throw new AppError(404,'Employee not found');const shift=await companyShift(workDate),existing=await Attendance.findOne({employeeId:employee.employeeId,workDate});if(existing?.workflow==='finalized'&&!req.body.reopen)throw new AppError(409,'Finalized attendance must be explicitly reopened before adjustment');const before=existing?.toObject()||null;let values;if(attendanceType==='sick'||attendanceType==='casual')values=leaveValues(employee,shift,workDate,attendanceType);else values={...calculateAttendance({employee,shift,workDate,punches:manualPunches(actualClockIn,actualClockOut)}),leaveType:null,workflow:'reviewed'};const record=await Attendance.findOneAndUpdate({employeeId:employee.employeeId,workDate},{$set:{...values,sourcePunchIds:existing?.sourcePunchIds||[],manuallyAdjusted:true,adjustmentReason:reason.trim()}},{upsert:true,new:true,runValidators:true,setDefaultsOnInsert:true});await AttendanceAdjustment.create({attendance:record._id,employeeId:record.employeeId,workDate,changedBy:req.user._id,before,after:record.toObject(),reason:reason.trim()});res.status(existing?200:201).json(record);}));
r.get('/exceptions',asyncHandler(async(req,res)=>{const q={};if(req.query.status)q.status=req.query.status;if(req.query.type)q.type=req.query.type;res.json(await AttendanceException.find(q).populate('attendance').sort('-createdAt').limit(500));}));
r.put('/exceptions/:id',asyncHandler(async(req,res)=>{const x=await AttendanceException.findByIdAndUpdate(req.params.id,{...req.body,resolvedBy:req.user._id,resolvedAt:new Date()},{new:true});if(!x)throw new AppError(404,'Exception not found');res.json(x);}));
r.get('/imports',asyncHandler(async(req,res)=>res.json(await ImportBatch.find().sort('-createdAt').limit(50))));
r.post('/finalize',asyncHandler(async(req,res)=>{const{startDate,endDate}=req.body;if(!/^\d{4}-\d{2}-\d{2}$/.test(startDate||'')||!/^\d{4}-\d{2}-\d{2}$/.test(endDate||'')||startDate>endDate)throw new AppError(400,'A valid start and end date are required');const result=await Attendance.updateMany({workDate:{$gte:startDate,$lte:endDate},workflow:{$ne:'needs_review'}},{workflow:'finalized',finalizedAt:new Date(),finalizedBy:req.user._id});res.json({finalized:result.modifiedCount});}));
r.get('/:id',asyncHandler(async(req,res)=>{const x=await Attendance.findById(req.params.id).populate('employee shiftId sourcePunchIds');if(!x)throw new AppError(404,'Attendance record not found');res.json(x);}));
r.put('/:id',asyncHandler(async(req,res)=>{const current=await Attendance.findById(req.params.id).populate('employee shiftId');if(!current)throw new AppError(404,'Attendance record not found');if(current.workflow==='finalized'&&!req.body.reopen)throw new AppError(409,'Finalized attendance must be explicitly reopened before adjustment');if(!req.body.reason?.trim())throw new AppError(422,'An adjustment reason is required');const attendanceType=req.body.attendanceType||'present';if(!['present','sick','casual'].includes(attendanceType))throw new AppError(422,'Choose Present, Sick Leave or Casual Leave');const before=current.toObject(),base=current.toObject();let calc;if(attendanceType==='sick'||attendanceType==='casual')calc=leaveValues(current.employee,current.shiftId,current.workDate,attendanceType);else calc={...calculateAttendance({employee:current.employee,shift:current.shiftId,workDate:current.workDate,punches:manualPunches(req.body.actualClockIn,req.body.actualClockOut)}),leaveType:null,workflow:'reviewed'};Object.assign(current,calc,{sourcePunchIds:base.sourcePunchIds,manuallyAdjusted:true,adjustmentReason:req.body.reason.trim(),workflow:'reviewed'});await current.save();await AttendanceAdjustment.create({attendance:current._id,employeeId:current.employeeId,workDate:current.workDate,changedBy:req.user._id,before,after:current.toObject(),reason:req.body.reason.trim()});res.json(current);}));
r.get('/',asyncHandler(async(req,res)=>{const page=Math.max(1,+req.query.page||1),limit=Math.min(500,+req.query.limit||100),q={};if(req.query.startDate||req.query.endDate)q.workDate={...(req.query.startDate&&{$gte:req.query.startDate}),...(req.query.endDate&&{$lte:req.query.endDate})};if(req.query.date)q.workDate=req.query.date;if(req.query.employeeId)q.employeeId=req.query.employeeId;if(req.query.status)q.conditions=req.query.status;const[data,total]=await Promise.all([Attendance.find(q).populate('employee shiftId').sort('-workDate employeeId').skip((page-1)*limit).limit(limit),Attendance.countDocuments(q)]);res.json({data,meta:pageMeta(page,limit,total)});}));export default r;
